function [] = LSA_EEGLAB_WarningMessagePopup()
%[] = LSA_EEGLAB_WarningMessagePopup()
%   Displays a warning message about the interpretability of the results
 
tmpT = {'Style', 'text', 'string'};
res = inputgui( 'geometry', { [1] [1] [1] [1] [1] [1] [1] [1] [1] [1] [1] [1] [1]}, ...
    'geomvert', [1 1 1 1 1 1 1 1 1 1 1 1 1], 'uilist', { ...
    { tmpT{:} , 'IMPORTANT: interpretation of results', 'fontweight', 'bold' } ...
    { tmpT{:} , ''} ...
    { tmpT{:} , 'Not all of the assumptions that make LSA interpretable will hold at each timepoint', 'fontweight', 'bold' } ...
    { tmpT{:} , 'Guaranteed interpretability only exists for the indicated channels. Therefore, this function will output ' }...
    { tmpT{:} , 'three EEG structures, and save three separate EEG datasets:' }...
    { tmpT{:} , '  - 1) EEG_LSA: This dataset contains the full filtered timecourse. ' , 'fontweight', 'bold' }...
    { tmpT{:} , '        IMPORTANTLY, there is no guarantee that each timepoint is interpretable. ' }...
    { tmpT{:} , '  - 2) EEG_LSA_nan: This dataset contains only the interpretable parts of the filtered timecourse. ' , 'fontweight', 'bold'  }...
    { tmpT{:} , '        All timepoints for which the assumptions do not hold are set to NaN. ' }...
    { tmpT{:} , '        Note that you might not be able to plot this output in EEGLAB due to its handling of NaNs. ' }...
    { tmpT{:} , '  - 3) EEG_LSA_selection: This dataset contains the average of the data within the time window selected by the user. ' , 'fontweight', 'bold'  }...
    { tmpT{:} , '        Hence, this dataset contains only 1 timepoint. All channels for which the assumptions do not hold are set to NaN. Therefore, the ' }...
    { tmpT{:} , '        output data are fully interpretable. Note that plotting this output in EEGLAB becomes difficult as there is only 1 timepoint.' }...
    } );
end

